Repository Testably/Testably.Abstractions, pull requests merged in 2023-07, with the labels that each got.

#325 doc: include information for local testing against the `RealFileSystem`
  .gitignore
  CONTRIBUTING.md
Labels: documentation

#316 refactor: Use central package management
  Directory.Packages.props
  Examples/Configuration/DependencyInjection.Tests/DependencyInjection.Tests.csproj
  Examples/Directory.Build.props
  Examples/Examples.sln
  Examples/ZipFile/ZipFile/ZipFile.csproj
  Source/Directory.Build.props
  Source/Testably.Abstractions.AccessControl/Testably.Abstractions.AccessControl.csproj
  Source/Testably.Abstractions.Compression/Testably.Abstractions.Compression.csproj
  Source/Testably.Abstractions.Interface/Testably.Abstractions.Interface.csproj
  Source/Testably.Abstractions.Testing/Testably.Abstractions.Testing.csproj
  Testably.Abstractions.sln
  Tests/Directory.Build.props
  Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/Testably.Abstractions.Tests.SourceGenerator.csproj
Labels: refactor

#328 feat: Add a sample Directory.Build.props
  CONTRIBUTING.md
  Directory.Build.props
  Testably.Abstractions.sln
Labels: documentation, enhancement

#329 fix: Remove single quotes from test
  Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs
Labels: bug

#333 chore(deps): update dependencies
  Directory.Packages.props
Labels: dependencies

#332 fix: Support relative paths with multiple subfolders in Directory.GetFiles
  Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
  Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs
Labels: bug

#335 feat: add `ToString` methods to simplify debugging
  Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensibility.cs
  Source/Testably.Abstractions.Testing/MockFileSystem.cs
  Source/Testably.Abstractions.Testing/MockRandomSystem.cs
  Source/Testably.Abstractions.Testing/MockTimeSystem.cs
  Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
  Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Labels: enhancement

#334 fix: parameter validation in `Path.GetFullPath`
  Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
  Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
  Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
  Source/Testably.Abstractions.Testing/InterceptionHandlerExtensions.cs
  Source/Testably.Abstractions.Testing/NotificationHandlerExtensions.cs
  Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
  Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
  Tests/Testably.Abstractions.Tests/FileSystem/Path/ExceptionTests.cs
Labels: bug

#336 fix: implementation of `Path.GetRelativePath`
  Source/Testably.Abstractions.Interface/Helpers/PathSystemBase.cs
  Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
  Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRelativePathTests.cs
Labels: bug

#337 fix: set stryker version to v3.7.1 on release builds
  .github/workflows/release.yml
Labels: bug

#340 chore: remove unnecessary reference
  Directory.Packages.props
  Examples/Directory.Build.props
Labels: dependencies

#341 feat: add `ToString` methods to simplify debugging (2)
  Source/Testably.Abstractions.Testing/MockFileSystem.cs
  Source/Testably.Abstractions.Testing/MockTimeSystem.cs
  Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
  Source/Testably.Abstractions.Testing/TimeProvider.cs
  Source/Testably.Abstractions.Testing/TimeSystem/TimeProviderMock.cs
Labels: enhancement

#342 docs: fix link in Codacy badge
  README.md
Labels: documentation

#343 feat: simplify initialization of file systems
  Source/Testably.Abstractions.Testing/FileSystemInitializer/DirectoryDescription.cs
  Source/Testably.Abstractions.Testing/FileSystemInitializer/FileDescription.cs
  Source/Testably.Abstractions.Testing/FileSystemInitializer/FileSystemInfoDescription.cs
  Source/Testably.Abstractions.Testing/FileSystemInitializer/FileSystemInitializer.cs
  Source/Testably.Abstractions.Testing/FileSystemInitializer/IFileSystemInitializer.cs
  Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
  Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryDescriptionTests.cs
  Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileDescriptionTests.cs
  Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs
Labels: enhancement
